name: Deploy GH Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout
        run: |
          mv ./public/* .
          rm README.md LICENSE *.js *.json
          rm -rf ./public
          rm -rf ./scripts
          rm -rf ./.github
          git add -A
          git commit -m "Deploy"
          git push && git checkout master

