name: Deploy GH Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to branch gh-pages
      - run: git checkout gh-pages
      - name: Extracting files from the public directory
      - run: mv ./public/* .
      - name: Commit deploy message
      - run: git commit -m "Deploy"
      - name: Push and Deploy 🚀
      - run: git push && git checkout master

